### ISSUE TITLE
Clarify user config naming convention

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/demo-deployer#32]
## Description

Docs for the demo-deployer and other demotron projects suggest naming the deployer credentials config file `[user].docker.local.json`. This is an important naming convention, but we don’t explain why (so users might assume it’s not important). We need to clarify the importance of this naming convention and normalize the documentation so we’re not saying the same-but-different things across repos.

## Details

The [user] part is quite important since that element gets used to make a composite key that is used to uniquely identify all the resources created by the deployment in the cloud provider and even New Relic. Typically, cloud providers (and New Relic) have multiple users creating resources. This ensures no one steps on each others' toes.

Side note, the 2nd part of the composite key is the first part of the deploy name, for example with a hello.json file, the hello part would become the 2nd part of the composite key.

As an example, If I deploy hello.json with my jsmith.docker.local.json file, then all my EC2 instances will be named jsmith-hello-[service_id].

## Notes

We also need to update dev site guides to reflect this naming convention.

**Comment by polfliet** [comment]
this has been clarified in the getting started guide, any file with .local.json is picked up automatically
