### ISSUE TITLE
Carry over Demotron MFF work

### ISSUE THREAD

**Issue by jpvajda** [newrelic/demo-deployer#86]
The work left over from Demotron's last MMF in JIRA.

This includes:
- [x] [Add invalid query behavior to javatron] (https://newrelic.atlassian.net/browse/DEMO-2565)
- [x] [Update mysql demo to include invalid query behavior] (https://newrelic.atlassian.net/browse/DEMO-2566)
- [x] [add a tutorial to demo-catalog] (https://newrelic.atlassian.net/browse/DEMO-2567)

**Comment by jpvajda** [comment]
@aswanson-nr will update this with details.

**Comment by aswanson-nr** [comment]
This is the leftovers of an MMF to add databases to the demotron ecosystem.

To do:
* Finish adding query error to Javatron (Almost done, PR here newrelic/demo-javatron#13
* Update the MySQL demo to include the query error
* Write a guide about how to add a database to a demo (@polfliet @jpvajda There is a separate issue for this in the demo-catalog repository, newrelic/demo-catalog#21. If we want to use that instead)

**Comment by jpvajda** [comment]
@aswanson-nr thanks! Do you mind adding an estimate label `sp:1` `sp:3` .... to give us a sense of how much effort this is?

**Comment by polfliet** [comment]
the work is done, hurray!

**Comment by polfliet** [comment]
Opening it so we see it in our board for the current sprint
