### ISSUE TITLE
Long running deployments become unresponsive

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/demo-deployer#89]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Long running deployments of Telco Lite eventually fall over and become unresponsive. I ran the deployment from 02/16/2021 and it become unresponsive around 03/15/2021. The only significant change in the deployment over that time period was disc usage. The discs were completely full for the UI and sim hosts, with the backend host approaching 100%. All hosts showed a continuous increase in disc usage over the deployment period. 

This is most likely due to a lack of log rotation in the Trons and the Simulator. Adding proper log rotation to these applications should alleviate the issue.

[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
Run the Telco Lite deployment for a few weeks.

## Expected Behavior
The deployment continues to run without loss of reporting or traffic.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
Deployed to AWS.

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by aswanson-nr** [comment]
Here is a link to the Telco Lite deployment config https://github.com/newrelic/demo-catalog/tree/main/catalog/telco_lite

**Comment by jpvajda** [comment]
Checking with @polfliet on the urgency for this bug.
