### ISSUE TITLE
Add hadolint check to CI/CD workflow

### ISSUE THREAD

**Issue by MoonlightKomorebi** [newrelic/demo-deployer#91]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Since we are going to be publishing a public Docker image for consumption, we should try to have automation to ensure best practice with the images we create. Hadolint is a tool I've used previously for this purpose (and might be an industry standard).

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

Hadolint runs & checks Dockerfile. This can always run (like for every commit), or if we can, ideally we set this up so that this check only runs when changes to the Dockerfile are present.

## Possible Solution

Create a new workflow, or update a pre-existing workflow where we can insert this new check.

**Comment by nr-kkenney** [comment]
identical issue in demo-simulator: newrelic/demo-simulator#15

if we implement this for one, we can just copy pasta the change into the other most likely.
